#!/bin/bash
# centos version - lists *all* updates as we don't get security metadata for centos

if [[ "$UID" != "0" ]]; then
  echo "Must be root to run this"; exit 1
fi

yum -d 0 list updates | grep -v 'Updated Packages' | awk '{ print $1 }'

