name             'harden'
maintainer       'Fraser Scott'
maintainer_email 'fraser.scott@gmail.com'
license          'MIT'
description      'Installs/Configures harden'
long_description 'Installs/Configures harden'
version          '0.4.5'

depends 'apt', '>= 2.6'
depends 'sensu_spec', '>= 0.10'
