name             'harden'
maintainer       'Fraser Scott'
maintainer_email 'fraser.scott@gmail.com'
license          'MIT'
description      'Installs/Configures harden'
long_description 'Installs/Configures harden'
version          '0.1.2'

depends 'apt'
depends 'sensu_spec', '~> 0.5'
