#!/bin/bash
# ubuntu version

if [[ "$UID" != "0" ]]; then
  echo "Must be root to run this"; exit 1
fi

grep -v '^#' /etc/apt/sources.list | grep 'deb ' | grep security > /etc/apt/harden_security.list

apt-get -o Dir::Etc::sourcelist="harden_security.list" -o Dir::Etc::sourceparts="-" update >/dev/null 2>&1

apt-get -o Dir::Etc::sourcelist="harden_security.list" -o Dir::Etc::sourceparts="-" update >/dev/null && apt-get --assume-no upgrade 2>/dev/null| grep '^  ' | sed 's/^ *//' | tr " " "\n"
